name: Main Validation

on:
  push:
    branches: ["master", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    permissions:
      contents: read
      packages: read
    with:
      build_image: true
      image_tag: main-test
